/*
** EPITECH PROJECT, 2025
** r-type
** File description:
** SettingsSceneUtils.cpp
*/

#include "SettingsSceneUtils.hpp"

#include "rtype/display/DisplayTypes.hpp"
#include "rtype/display/IDisplay.hpp"

std::string SettingsSceneUtils::keyToString(rtype::display::Key key) {
    switch (key) {
        case rtype::display::Key::A:
            return "A";
        case rtype::display::Key::B:
            return "B";
        case rtype::display::Key::C:
            return "C";
        case rtype::display::Key::D:
            return "D";
        case rtype::display::Key::E:
            return "E";
        case rtype::display::Key::F:
            return "F";
        case rtype::display::Key::G:
            return "G";
        case rtype::display::Key::H:
            return "H";
        case rtype::display::Key::I:
            return "I";
        case rtype::display::Key::J:
            return "J";
        case rtype::display::Key::K:
            return "K";
        case rtype::display::Key::L:
            return "L";
        case rtype::display::Key::M:
            return "M";
        case rtype::display::Key::N:
            return "N";
        case rtype::display::Key::O:
            return "O";
        case rtype::display::Key::P:
            return "P";
        case rtype::display::Key::Q:
            return "Q";
        case rtype::display::Key::R:
            return "R";
        case rtype::display::Key::S:
            return "S";
        case rtype::display::Key::T:
            return "T";
        case rtype::display::Key::U:
            return "U";
        case rtype::display::Key::V:
            return "V";
        case rtype::display::Key::W:
            return "W";
        case rtype::display::Key::X:
            return "X";
        case rtype::display::Key::Y:
            return "Y";
        case rtype::display::Key::Z:
            return "Z";
        case rtype::display::Key::Num0:
            return "0";
        case rtype::display::Key::Num1:
            return "1";
        case rtype::display::Key::Num2:
            return "2";
        case rtype::display::Key::Num3:
            return "3";
        case rtype::display::Key::Num4:
            return "4";
        case rtype::display::Key::Num5:
            return "5";
        case rtype::display::Key::Num6:
            return "6";
        case rtype::display::Key::Num7:
            return "7";
        case rtype::display::Key::Num8:
            return "8";
        case rtype::display::Key::Num9:
            return "9";
        case rtype::display::Key::Escape:
            return "Escape";
        case rtype::display::Key::LControl:
            return "LControl";
        case rtype::display::Key::LShift:
            return "LShift";
        case rtype::display::Key::LAlt:
            return "LAlt";
        case rtype::display::Key::LSystem:
            return "LSystem";
        case rtype::display::Key::RControl:
            return "RControl";
        case rtype::display::Key::RShift:
            return "RShift";
        case rtype::display::Key::RAlt:
            return "RAlt";
        case rtype::display::Key::RSystem:
            return "RSystem";
        case rtype::display::Key::Menu:
            return "Menu";
        case rtype::display::Key::LBracket:
            return "LBracket";
        case rtype::display::Key::RBracket:
            return "RBracket";
        case rtype::display::Key::SemiColon:
            return "Semicolon";
        case rtype::display::Key::Comma:
            return "Comma";
        case rtype::display::Key::Period:
            return "Period";
        case rtype::display::Key::Quote:
            return "Apostrophe";
        case rtype::display::Key::Slash:
            return "Slash";
        case rtype::display::Key::BackSlash:
            return "Backslash";
        case rtype::display::Key::Tilde:
            return "Grave";
        case rtype::display::Key::Equal:
            return "Equal";
        case rtype::display::Key::Dash:
            return "Hyphen";
        case rtype::display::Key::Space:
            return "Space";
        case rtype::display::Key::Return:
            return "Enter";
        case rtype::display::Key::BackSpace:
            return "Backspace";
        case rtype::display::Key::Tab:
            return "Tab";
        case rtype::display::Key::PageUp:
            return "PageUp";
        case rtype::display::Key::PageDown:
            return "PageDown";
        case rtype::display::Key::End:
            return "End";
        case rtype::display::Key::Home:
            return "Home";
        case rtype::display::Key::Insert:
            return "Insert";
        case rtype::display::Key::Delete:
            return "Delete";
        case rtype::display::Key::Add:
            return "Add";
        case rtype::display::Key::Subtract:
            return "Subtract";
        case rtype::display::Key::Multiply:
            return "Multiply";
        case rtype::display::Key::Divide:
            return "Divide";
        case rtype::display::Key::Left:
            return "Left";
        case rtype::display::Key::Right:
            return "Right";
        case rtype::display::Key::Up:
            return "Up";
        case rtype::display::Key::Down:
            return "Down";
        case rtype::display::Key::Numpad0:
            return "Numpad0";
        case rtype::display::Key::Numpad1:
            return "Numpad1";
        case rtype::display::Key::Numpad2:
            return "Numpad2";
        case rtype::display::Key::Numpad3:
            return "Numpad3";
        case rtype::display::Key::Numpad4:
            return "Numpad4";
        case rtype::display::Key::Numpad5:
            return "Numpad5";
        case rtype::display::Key::Numpad6:
            return "Numpad6";
        case rtype::display::Key::Numpad7:
            return "Numpad7";
        case rtype::display::Key::Numpad8:
            return "Numpad8";
        case rtype::display::Key::Numpad9:
            return "Numpad9";
        case rtype::display::Key::F1:
            return "F1";
        case rtype::display::Key::F2:
            return "F2";
        case rtype::display::Key::F3:
            return "F3";
        case rtype::display::Key::F4:
            return "F4";
        case rtype::display::Key::F5:
            return "F5";
        case rtype::display::Key::F6:
            return "F6";
        case rtype::display::Key::F7:
            return "F7";
        case rtype::display::Key::F8:
            return "F8";
        case rtype::display::Key::F9:
            return "F9";
        case rtype::display::Key::F10:
            return "F10";
        case rtype::display::Key::F11:
            return "F11";
        case rtype::display::Key::F12:
            return "F12";
        case rtype::display::Key::F13:
            return "F13";
        case rtype::display::Key::F14:
            return "F14";
        case rtype::display::Key::F15:
            return "F15";
        case rtype::display::Key::Pause:
            return "Pause";
        default:
            return "Unknown";
    }
}

std::string SettingsSceneUtils::actionToString(GameAction action) {
    switch (action) {
        case GameAction::MOVE_UP:
            return "Move Up";
        case GameAction::MOVE_DOWN:
            return "Move Down";
        case GameAction::MOVE_LEFT:
            return "Move Left";
        case GameAction::MOVE_RIGHT:
            return "Move Right";
        case GameAction::SHOOT:
            return "Shoot";
        case GameAction::CHANGE_AMMO:
            return "Change Ammo";
        case GameAction::PAUSE:
            return "Pause";
        default:
            return "Unknown";
    }
}
