/*
** EPITECH PROJECT, 2025
** r-type
** File description:
** PositionComponent.hpp
*/

#ifndef SRC_GAMES_RTYPE_SHARED_COMPONENTS_POSITIONCOMPONENT_HPP_
#define SRC_GAMES_RTYPE_SHARED_COMPONENTS_POSITIONCOMPONENT_HPP_

struct Position {
    float x;
    float y;
};

#endif  // SRC_GAMES_RTYPE_SHARED_COMPONENTS_POSITIONCOMPONENT_HPP_
